// The languages used in the main content of the website

export const languages = [
  "acchami",
  "angika",
  "awadhi",
  "bahing",
  "baitadeli",
  "bajhangi",
  "bajjika",
  "bajureli",
  "bambule",
  "bantawa",
  "bhojpuri",
  "bhojpuri_deva",
  "bn",
  "bo",
  "chamling",
  "chhantyal",
  "chhepang",
  "chhintang",
  "dadeldhuri",
  "danuwar",
  "dhimal",
  "dolpo",
  "doteli",
  "dumi",
  "dungmali",
  "en",
  "haryanvi",
  "hi",
  "jirel",
  "khas",
  "kisan",
  "koch",
  "koich",
  "kumal",
  "lhomi",
  "limbu",
  "lohorong",
  "magahi",
  "maithili",
  "maithili_deva",
  "majhi",
  "marwadi",
  "magar-dhut",
  "magar-kham",
  "nb",        // Nepal Bhasa
  "nb-balami",
  "nb-dolakha",
  "nb-gopali",
  "nb-khwopa", // Nepal Bhasa (Khwopa)
  "ne",
  "nsl",
  "pali",
  "palideva",
  "palinewa",
  "puma",
  "punjabi",
  "rajbanshi",
  "santhali",
  "sindhi",
  "skt",
  "sktnewa",
  "sonaha",
  "syuba",
  "tajpuriya",
  "tamu",
  "thami",
  "tharu-kochila",
  "tharu-lampuchwa",
  "tharu-rana",
  "tharu-saptariya",
  "tmg",
  "tmgd",
  "thulung",
  "ur",
  "urav",
  "xsr",
  "yakkha",
  "yakthung",
] as const;

export type Language = (typeof languages)[number];