// The languages used in the main content of the website

export const languages = [
  "acchami",
  "angika",
  "awadhi",
  "bahing",
  "baitadeli",
  "bajhangi",
  "bajjika",
  "bajureli",
  "bambule",
  "bantawa",
  "bhojpuri",
  "bhojpuri_deva",
  "bn",
  "bo",
  "chamling",
  "chhantyal",
  "chhepang",
  "chhintang",
  "dadeldhuri",
  "dhimal",
  "dolakha", // Matches nbd in your previous logic, now standardized as 'dolakha'
  "doteli",
  "dumi",
  "dungmali",
  "en",
  "haryanvi",
  "hi",
  "jirel",
  "kumal",
  "lhomi",
  "lohorong",
  "magahi",
  "maithili",
  "maithili_deva",
  "majhi",
  "marwadi",
  "mgrkham",
  "nb",
  "ne",
  "nsl",
  "pali",
  "palideva",
  "palinewa",
  "puma",
  "punjabi",
  "rajbanshi",
  "sindhi",
  "skt",
  "sktnewa",
  "sonaha",
  "tajpuriya",
  "tamu",
  "thami",
  "tharu-kochila",
  "tharu-lampuchwa",
  "tharu-rana",
  "tharu-saptariya",
  "tmg",
  "tmgd",
  "ur",
  "urav",
  "xsr",
  "yakkha",
] as const;

export type Language = (typeof languages)[number];